import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {test} from 'node:test';
import {digestContract,digestPackManifest} from '@abh/contracts/digest';
import {contract} from '../src/data/journal.ts';
import {readCapabilitySchema} from '../src/extensions/read-capability-schema.ts';
import {preparePackCapabilities} from '../src/extensions/prepare-pack-capabilities.ts';
import {packManifest} from './pack-fixture.ts';
const ref=(type:string)=>({type,id:randomUUID(),version:1});
const options=()=>({deadline:Date.now()+5000,signal:new AbortController().signal});
test('exact registered Schema reads actual bounded bytes and isolates reused source buffers',async()=>{
 const raw={...await packManifest(),capabilities:{provides:[{kind:'abh.tool',id:'org.example.hello.tool',version:'1.0.0'}],requires:[]}};
 const {signaturePayload:_,...digests}=await digestPackManifest(raw),pack=contract('PackManifest',{...raw,integrity:{...raw.integrity,...digests}});
 const binding={capability:pack.capabilities.provides[0]!,schemaPath:'input.json',implementationRef:ref('abh.artifact'),healthRef:ref('abh.artifact'),permissionEnvelope:pack.permissions};
 const source=(text:string)=>({refs:['input.json'],open:async()=>({async *[Symbol.asyncIterator](){yield new TextEncoder().encode(text);}})});
 const [entry]=await preparePackCapabilities(pack,ref('abh.installed-pack'),[binding],source('abc'),options(),{schema:async()=>{},implementation:async()=>{}});
 const read=(s=source('abc'))=>readCapabilitySchema(pack,entry!,s,options());
 assert.equal(new TextDecoder().decode(await read()),'abc');
 for(const text of ['abd','ab','abcd'])await assert.rejects(read(source(text)),{code:'PRECONDITION_FAILED'});
 const buffer=Buffer.from('abc');
 const bytes=await read({refs:['input.json'],open:async()=>({async *[Symbol.asyncIterator](){yield buffer;buffer.fill(0);}})});
 assert.equal(new TextDecoder().decode(bytes),'abc');bytes.fill(0);assert.equal(new TextDecoder().decode(await read()),'abc');
 for(const patch of [{implementationRef:ref('abh.artifact')},{schemaDigest:'sha256:'+'0'.repeat(64)}])await assert.rejects(readCapabilitySchema(pack,{...entry!,...patch},source('abc'),options()),{code:'PRECONDITION_FAILED'});
 const changed={...entry!,permissionEnvelope:{...entry!.permissionEnvelope,commands:['org.example.denied']}};changed.registrationDigest=await digestContract('PackCapabilityRegistration',changed);
 await assert.rejects(readCapabilitySchema(pack,changed,source('abc'),options()),{code:'FORBIDDEN'});
 await assert.rejects(read({...source('abc'),refs:['input.json','input.json']}),{code:'PRECONDITION_FAILED'});
 let signal:AbortSignal|undefined;
 await assert.rejects(readCapabilitySchema(pack,entry!,{refs:['input.json'],open:async(_path,work)=>{signal=work.signal;return {async *[Symbol.asyncIterator](){await new Promise(()=>{});}};}},{...options(),deadline:Date.now()+30}),{code:'DEPENDENCY_TIMEOUT'});
 assert.equal(signal?.aborted,true);
 let returned=0;
 await assert.rejects(readCapabilitySchema(pack,entry!,{refs:['input.json'],open:async()=>({[Symbol.asyncIterator](){return {next:()=>new Promise<IteratorResult<Uint8Array>>(()=>{}),return:async()=>{returned++;return {done:true as const,value:undefined};}};}})},{...options(),deadline:Date.now()+30}),{code:'DEPENDENCY_TIMEOUT'});
 assert.equal(returned,1);
 const stop=new AbortController();stop.abort();await assert.rejects(readCapabilitySchema(pack,entry!,source('abc'),{...options(),signal:stop.signal}),{code:'DEPENDENCY_TIMEOUT'});
});
